In [ ]:
import numpy as np

### Exercicio:
1. Crie um array numpy com valores partindo de 10 até 49
2. Crie uma matriz numpy de 2 por 2 preenchida com 1's
3. Crie uma matriz numpy 3 por 2 de floats preenchida com 1's
4. Crie uma matriz 4 por 4 de integers preenchida com 5's
5. Crie uma matriz identidade de 3 por 3
6. Crie um array numppy prrenchido 3 integers aleatórias entre 1 e 10


In [ ]:
# Questão 1:

np.arange(10,50)

In [ ]:
# Questão 2:

np.ones((2,2), dtype=int)

array([[1, 1],
       [1, 1]])

In [ ]:
# Questão 3:

np.ones((3,2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# Questão 4:

np.full((4,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
# Questão 5:

np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Questão 6:

np.random.randint(1,10,3)

array([9, 7, 8])

### Exercício:
1. Dado o array X = np.array(['A','B','C','D','E'])
Mostre o último elemento
2. Mostre os primeiros 3 elementos
3. Mostre só os elementos do meio
4. Inverta a ordem do array
5. Mostre os elementos nas posições impar.
6. De acordo com a matriz, mostre a primeira linha X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
7. Mostre o primeiro elemento na primeira linha
8. Mostre a linha intermediária
9. Os primeiros 2 elementos das duas primeiras linhas
10. Os últimos 2 elementos das duas últimas linhas

In [ ]:
# Questão 1:

X = np.array(['A','B','C','D','E'])

X[-1]

'E'

In [ ]:
# Questão 2:

X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

In [ ]:
# Questão 3:

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [ ]:
# Questão 4:

X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [ ]:
# Questão 5:

X[1::2]

array(['B', 'D'], dtype='<U1')

In [ ]:
# Questão 6:

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

In [ ]:
# Questão 7:

X[0,0]


1

In [ ]:
# Questão 8:

X[1:-1]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Questão 9:

X[:2,:2]


array([[1, 2],
       [5, 6]])

In [ ]:
# Questão 10:

X[-2:,-2:]

array([[11, 12],
       [15, 16]])

### Exercicios:
1. De acordo com o array X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
faça a soma
2. Faça a média
3. Dada a matriz faça a soma das colunas X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
4. Faça a média das linhas
5. Dado o array X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
Mostre o elemento de maior valor

In [ ]:
# Questão 1:

X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

np.sum(X)

43

In [ ]:
#Questão 2:

np.average(X)

4.777777777777778

In [ ]:
# Questão 3:

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

np.sum(X, axis=0)


array([28, 32, 36, 40])

In [ ]:
# Questão 4:

np.average(X, axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

In [ ]:
# Questão 5:

X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

np.max(X)

10