In [1]:
import numpy as np

### Exercicios

1. Replace all occurrences of 3 with 10, arr = np.array([1, 2, 3,3,3,3,3, 4, 5])
2. Find common elements between the two arrays, arr1 = np.array([1, 2, 3, 4, 5]), arr2 = np.array([3, 4, 5, 6, 7])
3. Reshape the array into a 2x4 matrix, arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
4. Remove duplicate elements, arr = np.array([1, 2, 2, 3, 4, 4, 5, 6, 6])
5. Split the array into three sub-arrays, arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
6. Perform element-wise multiplication, arr1 = np.array([1, 2, 3, 4]), arr2 = np.array([5, 6, 7, 8])


In [2]:
# Questão 1:

arr = np.array([1, 2, 3,3,3,3,3, 4, 5])

arr[arr == 3] = 10
arr

array([ 1,  2, 10, 10, 10, 10, 10,  4,  5])

In [3]:
# Questão 2:

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

np.intersect1d(arr1, arr2)


array([3, 4, 5])

In [4]:
# Questão 3:

x = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
# Questão 4:

arr = np.array([1, 2, 2, 3, 4, 4, 5, 6, 6])

np.unique(arr)



array([1, 2, 3, 4, 5, 6])

In [6]:
# Questão 5:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

np.array_split(arr,3)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [7]:
# Questão 6:

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

np.multiply(arr1, arr2)

array([ 5, 12, 21, 32])

--------------

**Bora praticar!**  
  
Transforme o csv **dados_artificiais**, que está na pasta **dados**, para um numpy array (matriz)

In [1]:
import numpy as np

In [6]:
matriz = np.loadtxt("C:\\Users\\bia_c\\OneDrive\\Área de Trabalho\\Exercícios\\aula 3\\dados_artificiais.txt", skiprows=1, usecols=(1, 2, 3))


In [7]:
matriz

array([[ 1.788811, 65.648102,  0.      ],
       [ 1.566784, 76.642768,  0.      ],
       [ 2.092193, 55.468185,  1.      ],
       [ 1.782471, 67.281997,  1.      ],
       [ 1.735767, 69.289008,  0.      ],
       [ 1.686975, 56.840051,  0.      ],
       [ 1.797105, 65.208973,  1.      ],
       [ 1.187349, 48.164764,  0.      ],
       [ 1.595891, 45.410648,  1.      ],
       [ 1.396282, 67.930113,  0.      ],
       [ 1.606148, 67.719604,  0.      ],
       [ 1.70759 , 45.609333,  0.      ],
       [ 1.735513, 64.845452,  0.      ],
       [ 1.672055, 39.705952,  1.      ],
       [ 1.723377, 50.05888 ,  1.      ],
       [ 1.684574, 56.545087,  1.      ],
       [ 1.733259, 37.512188,  0.      ],
       [ 1.7579  , 57.362422,  0.      ],
       [ 1.913338, 69.307246,  1.      ],
       [ 1.456048, 69.342337,  0.      ]])

Agora utilize esta matriz para calcular o IMC, utilizando a equação

```
IMC = peso / altura**2
```
e insira na nova tabela

In [ ]:
imc = [matriz[i][1]/(matriz[i][0]**2) for i in range(len(matriz))]

imc

[20.516026942563006,
 31.221439684559105,
 12.671862911844382,
 21.176487571306087,
 22.9975456097574,
 19.972717793575036,
 20.191122114932906,
 34.16431008742802,
 17.829996098895624,
 34.84304150287812,
 26.250844980187235,
 15.641792322967879,
 21.52899612253168,
 14.202163088357656,
 16.854681239064504,
 19.925750579824385,
 12.486636478786007,
 18.56261460033422,
 18.931945612244615,
 32.707480416323556]

In [ ]:
imc_list = list()

for pessoa in matriz:
    altura = pessoa[0]
    peso = pessoa[1]
    imc = (peso/altura**2)
    imc_list.append(imc)

    imc_array = np.array(imc_list)

new_table = np.concatenate((matriz, imc_array.reshape(-1,1)), axis=1)

new_table

array([[ 1.788811  , 65.648102  ,  0.        , 20.51602694],
       [ 1.566784  , 76.642768  ,  0.        , 31.22143968],
       [ 2.092193  , 55.468185  ,  1.        , 12.67186291],
       [ 1.782471  , 67.281997  ,  1.        , 21.17648757],
       [ 1.735767  , 69.289008  ,  0.        , 22.99754561],
       [ 1.686975  , 56.840051  ,  0.        , 19.97271779],
       [ 1.797105  , 65.208973  ,  1.        , 20.19112211],
       [ 1.187349  , 48.164764  ,  0.        , 34.16431009],
       [ 1.595891  , 45.410648  ,  1.        , 17.8299961 ],
       [ 1.396282  , 67.930113  ,  0.        , 34.8430415 ],
       [ 1.606148  , 67.719604  ,  0.        , 26.25084498],
       [ 1.70759   , 45.609333  ,  0.        , 15.64179232],
       [ 1.735513  , 64.845452  ,  0.        , 21.52899612],
       [ 1.672055  , 39.705952  ,  1.        , 14.20216309],
       [ 1.723377  , 50.05888   ,  1.        , 16.85468124],
       [ 1.684574  , 56.545087  ,  1.        , 19.92575058],
       [ 1.733259  , 37.

| IMC             | Categoria           |   |
|-----------------|---------------------|---|
| abaixo de 16,00 | Baixo peso Grau III |   |
| 16,00 a 16,99   | Baixo peso Grau II  |   |
| 17,00 a 18.49   | Baixo peso Grau I   |   |
| 18,50 a 24,99   | Peso ideal          |   |
| 25,00 a 29,99   | Sobrepeso           |   |
| 30,00 a 34,99   | Obesidade Grau I    |   |
| 35,00 a 39,99   | Obesidade Grau II   |   |
| 40,0 e acima    | Obesidade Grau III  |   |

Agora utilize a tabela acima para indicar a qual categoria cada valor de IMC se enquadra. Insira novamente na tabela.

In [ ]:
category_list = []
for pessoa in new_table:
    imc = pessoa[-1]
    if imc < 16.00:
        category_list.append('Baixo peso Grau III')
    elif imc >= 16.00:
        category_list.append('Baixo peso Grau II')
    elif imc >= 17.00:
        category_list.append('Baixo peso Grau I')
    elif imc >= 18.50:
        category_list.append('Peso ideal')
    elif imc >= 25.00:
        category_list.append('Sobrepeso')
    elif imc >= 30.00:
        category_list.append('Obesidade Grau I')
    elif imc >= 35.00:
        category_list.append('Obesidade Grau II')
    elif imc >= 40.00:
        category_list.append('Obesidade Grau III')

category_array = np.array(category_list)    

In [ ]:
final_table = np.concatenate((new_table, category_array.reshape(-1,1)), axis=1)
final_table

array([['1.788811', '65.648102', '0.0', '20.516026942563006',
        'Baixo peso Grau II'],
       ['1.566784', '76.642768', '0.0', '31.221439684559105',
        'Baixo peso Grau II'],
       ['2.092193', '55.468185', '1.0', '12.671862911844382',
        'Baixo peso Grau III'],
       ['1.782471', '67.281997', '1.0', '21.176487571306087',
        'Baixo peso Grau II'],
       ['1.735767', '69.289008', '0.0', '22.9975456097574',
        'Baixo peso Grau II'],
       ['1.686975', '56.840051', '0.0', '19.972717793575036',
        'Baixo peso Grau II'],
       ['1.797105', '65.208973', '1.0', '20.191122114932906',
        'Baixo peso Grau II'],
       ['1.187349', '48.164764', '0.0', '34.16431008742802',
        'Baixo peso Grau II'],
       ['1.595891', '45.410648', '1.0', '17.829996098895624',
        'Baixo peso Grau II'],
       ['1.396282', '67.930113', '0.0', '34.84304150287812',
        'Baixo peso Grau II'],
       ['1.606148', '67.719604', '0.0', '26.250844980187235',
        'Ba

### Criar header e salvar o txt com os dados, separado por vírgulas

In [ ]:
header = np.array(['Altura', 'Peso', 'Sexo', 'IMC', 'Categoria'])

table = np.vstack([header, final_table])
table




array([['Altura', 'Peso', 'Sexo', 'IMC', 'Categoria'],
       ['1.788811', '65.648102', '0.0', '20.516026942563006',
        'Baixo peso Grau II'],
       ['1.566784', '76.642768', '0.0', '31.221439684559105',
        'Baixo peso Grau II'],
       ['2.092193', '55.468185', '1.0', '12.671862911844382',
        'Baixo peso Grau III'],
       ['1.782471', '67.281997', '1.0', '21.176487571306087',
        'Baixo peso Grau II'],
       ['1.735767', '69.289008', '0.0', '22.9975456097574',
        'Baixo peso Grau II'],
       ['1.686975', '56.840051', '0.0', '19.972717793575036',
        'Baixo peso Grau II'],
       ['1.797105', '65.208973', '1.0', '20.191122114932906',
        'Baixo peso Grau II'],
       ['1.187349', '48.164764', '0.0', '34.16431008742802',
        'Baixo peso Grau II'],
       ['1.595891', '45.410648', '1.0', '17.829996098895624',
        'Baixo peso Grau II'],
       ['1.396282', '67.930113', '0.0', '34.84304150287812',
        'Baixo peso Grau II'],
       ['1.606148'

In [ ]:
filename = 'dados_imc.txt'

np.savetxt(filename, table, delimiter=', ', fmt='%s')
print(f"Arquivo '{filename}' salvo com sucesso.")

Arquivo 'dados_imc.txt' salvo com sucesso.
